### ISSUE TITLE
Request: add this app to brew cask

### ISSUE THREAD

**Issue by phlinhng** [jesse-c/AutoVolume#1]
Thanks for your app for solving my problem! I usually used 100% with my own external speaker in my room but every time when  I bring my laptop outside and plug in my earphone, I always scared by the extremely loudness. It will be convenient if AutoVolume can be install through brew cask.

**Comment by jesse-c** [comment]
No worries! That can definitely be done. I've actually made some small Cask contributions to Homebrew before. I'll get around to this _soon_.

Edit: Also, out of curiosity, have you used this on macOS Mojave?

**Comment by phlinhng** [comment]
Yes I did use it on macOS Mojave and find out that AutoVolume wouldn't automatically start up after booting. But the idea is still useful for me. Will be better if you can fix it on macOS Mojave.

**Comment by jesse-c** [comment]
I've submitted a PR.

Do you mind making a new issue for the automatic startup failing? :)

**Comment by jesse-c** [comment]
PR's been merged.
